runtime: python27
api_version: 1
threadsafe: true

default_expiration: "0d 0h"

handlers:
- url: /$
  static_files: index.html
  upload: index\.html

- url: /src
  static_dir: src
  http_headers:
    Cache-Control: no-cache

- url: /images
  static_dir: images

- url: /bin
  static_dir: bin

skip_files:
- ^\.DS_Store
- ^\.gitignore
- ^\.git
- ^server/.*$
- ^server/node_modules$
