runtime: python27
api_version: 1
threadsafe: true

default_expiration: "0d 0h"

handlers:
- url: /$
  static_files: index.html
  upload: index\.html
  secure: never

- url: /src
  static_dir: src
  http_headers:
    Cache-Control: no-cache
  secure: never

- url: /images
  static_dir: images
  secure: never

- url: /bin
  static_dir: bin
  secure: never

skip_files:
- ^\.DS_Store
- ^\.gitignore
- ^\.git
- ^server/.*$
- ^server/node_modules$
